### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by AFAgarap** [jmebia/barangay696-CBIS#1]
Hello, @jmebia 

I was wondering if you have already done something with the query in your `DBModel.java`, lines 54-55 that read:

```
preparedStatement = connection.prepareStatement("SELECT * FROM " + dbTableName + ";");
resultSet = preparedStatement.executeQuery();
```

I know you are aware that that kind of query is susceptible to SQLi. This is just a gentle reminder, perhaps try parameterized query?

```
preparedStatement = connection.prepareStatement("SELECT * FROM ?;");
preparedStatement.setString(1, dbTableName);
resultSet = preparedStatement.executeQuery();
```

Yes, it is just a query to get all data from your database's table, but it doesn't hurt to be extra careful, right? ;)

**Comment by jmebia** [comment]
Oh right, thanks.

**Comment by jmebia** [comment]
I'm getting this error:

> com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''inihabitant'' at line 1

**Comment by AFAgarap** [comment]
@jmebia Then you may just check the docs for MySQL and/or Java.

**Comment by jmebia** [comment]
Just found out after comparing the current code with my previous one that it isn't possible since the syntax for mySQL for SELECT should be:
`SELECT * FROM table;`

What prepared statement's parameterized query does is this:
`SELECT * FROM ?` > `SELECT * FROM 'table';`

I know it's kinda weird. So I think parameterized query is good only for other things that uses actual parameters like:
`SELECT * FROM table WHERE user_id=?` > `SELECT * FROM table WHERE user_id='1'`

Thanks anyways, atleast I learned something new. :smile:

**Comment by AFAgarap** [comment]
Oh, yes. That's right. My bad, I forgot. Parameterized queries do convert the parameters to string, making it an invalid syntax for the query at hand.
